### ISSUE TITLE
Wrong Kernelversionstring in /etc/kernel/postinst.d/initramfs-rebuild

### ISSUE THREAD

**Issue by JanBaudis** [brutus-downunder/LUKS-on-Raspberry-Pi4#1]
Hi brutus-downunder,

i think i just stumbled onto a potential bug. I think the script from robpol86 regarding the kernel rebuild (/etc/kernel/postinst.d/initramfs-rebuild) is written for a 32bit kernel. Since the Description uses a 64bit one, all _-v7+_ should be replaced by _-v8+_ if i am not mistaken.
Btw. thx for your Guide!

Best Regards

**Comment by brutus062** [comment]
Yes, you are right.
Changes made.
Thanks

**Comment by JanBaudis** [comment]
Thx for confirming and fixing 😄
